taxonomies:
  - key: group
    single: true
    setAsPageParent: true
    plugins:
      orderByDirection: asc
      permalink: ':term/:archiveIndex'
      orderBy:
        - 'title'
    themes:
      orderByDirection: asc
      permalink: ':term/:archiveIndex'
      orderBy:
        - 'title'
    bundles:
      orderByDirection: asc
      permalink: ':term/:archiveIndex'
      orderBy:
        - 'title'

# Page configurations
termArchivePages:
  layout: noBoxNoTitle
