site:
  about:
    siteName: Orchid
    siteDescription: A beautiful and truly unique documentation engine and static site generator.
    avatar: 'assets/media/avatar.jpg'

theme:
  social:
    other:
      - link: 'https://orchid.netlify.com/'
        label: 'Home'
        icon: 'fas fa-home'
      - link: 'https://github.com/JavaEden/Orchid'
        label: 'Github'
        icon: 'fab fa-github'
      - link: 'https://twitter.com/OrchidSSG'
        label: 'Twitter'
        icon: 'fab fa-twitter'
  primaryColor: '#7E80CF'
  bannerColor: '#444444'
  linkColor: '#7E80CF'
  trianglifyOptions:
    x_colors: 'BuPu'
    cell_size: 55
    seed: 1
  menu:
    - type: 'page'
      title: 'Home'
      itemId: 'Home'
    - type: 'wikiSections'
    - type: 'page'
      itemId: 'Changelog'
  sidebarBackground: 'black'
  sidebarBackgroundType: GRADIENT
  sidebarShadow: false
  useBackgroundTexture: false
  colors:
    purple: '#7E83C4'
    black: '#444444'
  palette:
    primary: 'PURPLE'
    link: 'BLUE'

services:
  publications:
    stages:
      - type: githubReleases
        repo: 'JavaEden/Orchid'

kotlindoc:
  sourceDirs:
    - '../../main/java'
    - '../../main/kotlin'

changelog:
  includeMinorVersions: true
  includeReleaseNotes: true
  allVersions:
    url: "#{'changelog'|baseUrl}"

allPages:
  extraCss:
    - "inline:sidecar.css: .gitter-chat-embed { margin-top: 50px; }"
    - 'assets/css/plugins.scss'
    - 'assets/font/Biko-Black/styles.css'
    - 'assets/font/BLOKKNeue-Regular/styles.css'
    - 'assets/css/extras.scss'
  extraJs:
    - "inline:sidecar.js:((window.gitter = { }).chat = { }).options = { room: 'JavaEden/Orchid' }; "
    - "https://sidecar.gitter.im/dist/sidecar.v1.js"
    - "assets/js/simpleFilter.js"
  components:
    - type: "pageContent"
    - type: "prism"
      githubTheme: 'duotone-light'
      languages:
        - kotlin
        - java
        - groovy
        - yaml
        - asciidoc
        - markdown